coverage:
  status:
    project:
      default:
        target: 75%    # the required coverage value
        threshold: 10%  # the leniency in hitting the target

ignore:
  - "NQueensSimulation/Assets/Plugins"
  - "NQueensSimulation/Assets/_Demo" 
  - "NQueensSimulation/Assets/Tests"  