#   Automated Build Pipeline
#   Uses: GameCI, 
#   From: GameCI, and Fathom7

name: Automated Builds
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  BuildProject:
      name: Build for ${{ matrix.targetPlatform }}
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          targetPlatform:
            - StandaloneOSX # Build a macOS standalone (Intel 64-bit).
            - StandaloneWindows64 # Build a Windows 64-bit standalone.
            - StandaloneLinux64 # Build a Linux 64-bit standalone.
            - WebGL # WebGL.
      steps:
        - name: Checkout Repo
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
            lfs: true
        - name: Cache Project Library for next Build
          uses: actions/cache@v2
          with:
            path: NQueensSimulation
            key: Library-${{ matrix.targetPlatform }}
            restore-keys: Library-
        - uses: game-ci/unity-builder@v2
          env:
            UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          with:
            targetPlatform: ${{ matrix.targetPlatform }}
            versioning: Semantic